language: python
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
    env: TOXENV=py37
  - python: 3.7
    dist: xenial
    sudo: true
    env: TOXENV=codestyle

install:
  - pip install tox
#  - pip install -r requirements.txt

script: tox
